# Tensorflow fundamental

In [158]:
import tensorflow as tf

In [159]:
tf.__version__

'2.15.0'

In [160]:
scaler = tf.constant(7)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [161]:
scaler.ndim

0

In [162]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [163]:
vector.ndim

1

In [164]:
matrix = tf.constant([[10, 20], [30, 40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [165]:
matrix.ndim

2

In [166]:
new_matrix = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]], dtype=tf.float16)
new_matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float16)>

In [167]:
new_matrix.ndim, new_matrix.shape

(2, TensorShape([3, 3]))

In [168]:
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [169]:
tensor.ndim, tensor.shape

(3, TensorShape([3, 2, 3]))

# Creating tensors with `tf.Variable`

In [170]:
tensor1 = tf.Variable([10, 8])
tensor2 = tf.constant([10, 8])

In [171]:
tensor1, tensor2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  8], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>)

In [172]:
tensor1[0].assign(20)
tensor1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([20,  8], dtype=int32)>

# Creating random tensors

In [173]:
random_1 = tf.random.Generator.from_seed(17)
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(7)
random_2 = random_2.normal(shape=(3, 2))

In [174]:
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.5420506 , -0.16822556],
        [-0.4390865 , -0.4129243 ],
        [ 0.35877243, -1.9095894 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>)

In [175]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

# Shuffle the order of elements in a tensor

In [176]:
not_shuffled = tf.constant([[1, 2],
                            [3, 4],
                            [5, 6]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 6],
       [1, 2],
       [3, 4]], dtype=int32)>

In [177]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [178]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [179]:
matrix = tf.constant([[10, 20], [30, 40], [50, 60]])
tf.random.set_seed(42)
tf.random.shuffle(matrix, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]], dtype=int32)>

In [180]:
ones = tf.ones(shape=(10, 7))
ones

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [181]:
zeros = tf.zeros(shape=(4, 4))
zeros

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turn NumPy arrays into tensors

In [182]:
import numpy as np

In [183]:
numpy_a = np.arange(1, 25, dtype=np.int32)
numpy_a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [184]:
A = tf.constant(numpy_a, shape=(3, 8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [185]:
numpy_b = np.arange(1, 25, dtype=np.int32)
numpy_b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [186]:
B = tf.constant(numpy_b, shape=(6, 4))
B

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]], dtype=int32)>

# Getting information from tensors

In [187]:
tensor = tf.zeros(shape=(2, 3, 4, 5))
tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [188]:
tensor.shape,

(TensorShape([2, 3, 4, 5]),)

In [189]:
tf.size(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [190]:
tensor.ndim

4

In [191]:
tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [192]:
tensor[:2, :2, :2, :]

<tf.Tensor: shape=(2, 2, 2, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [193]:
tensor = tf.constant([[10, 7], [3, 4]])
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [194]:
new_tensor = tensor[..., tf.newaxis]
new_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [195]:
tensor_3 = tf.expand_dims(new_tensor, axis=-1)
tensor_3

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[10]],

        [[ 7]]],


       [[[ 3]],

        [[ 4]]]], dtype=int32)>

In [196]:
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40],
       [50, 60]], dtype=int32)>

In [197]:
new_matrix = matrix[..., tf.newaxis]
new_matrix

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[10],
        [20]],

       [[30],
        [40]],

       [[50],
        [60]]], dtype=int32)>

In [198]:
matrix_3 = tf.expand_dims(new_matrix, axis=1)
matrix_3

<tf.Tensor: shape=(3, 1, 2, 1), dtype=int32, numpy=
array([[[[10],
         [20]]],


       [[[30],
         [40]]],


       [[[50],
         [60]]]], dtype=int32)>

In [199]:
tf.expand_dims(matrix, axis=0)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[10, 20],
        [30, 40],
        [50, 60]]], dtype=int32)>

In [200]:
tf.expand_dims(matrix, axis=1)

<tf.Tensor: shape=(3, 1, 2), dtype=int32, numpy=
array([[[10, 20]],

       [[30, 40]],

       [[50, 60]]], dtype=int32)>

# Manipulating tensors (tensor operations)
Basic operations

`+`, `-`, `*`, `/`

In [201]:
tensor = tf.constant([[10, 7],
                      [23, 34]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [23, 34]], dtype=int32)>

In [202]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [230, 340]], dtype=int32)>

In [203]:
tensor -10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [13, 24]], dtype=int32)>

In [204]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [33, 44]], dtype=int32)>

In [205]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [2.3, 3.4]])>

# Matrix multiplication

In [206]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [23, 34]], dtype=int32)>

In [207]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 261,  308],
       [1012, 1317]], dtype=int32)>

In [208]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 100,   49],
       [ 529, 1156]], dtype=int32)>

In [209]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])
y = tf.constant([[7, 8], [9, 10], [11, 12]])

In [210]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [211]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [212]:
# tf.matmul(x, y)

In [213]:
x.shape, y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [214]:
y = tf.reshape(y, shape=(2, 3))

In [215]:
tf.matmul(x, y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [216]:
x.shape, y.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [217]:
x = tf.reshape(x, shape=(2, 3))

In [218]:
tf.matmul(tf.reshape(x, shape=(3, 2)), y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [219]:
x, tf.transpose(x)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>)

In [220]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])
y = tf.constant([[7, 8], [9, 10], [11, 12]])

In [221]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [222]:
y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [223]:
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [224]:
tf.tensordot(tf.transpose(x), y, axes=0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[ 7,  8],
         [ 9, 10],
         [11, 12]],

        [[21, 24],
         [27, 30],
         [33, 36]],

        [[35, 40],
         [45, 50],
         [55, 60]]],


       [[[14, 16],
         [18, 20],
         [22, 24]],

        [[28, 32],
         [36, 40],
         [44, 48]],

        [[42, 48],
         [54, 60],
         [66, 72]]]], dtype=int32)>

In [225]:
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

# Changing the datatype of a tensor

In [226]:
tensor = tf.constant([1.7, 7.4])
tensor, tensor.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [227]:
tensor_2 = tf.constant([7, 10])
tensor_2, tensor_2.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 tf.int32)

In [228]:
A = tf.cast(tensor, dtype=tf.float64)
A

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([1.70000005, 7.4000001 ])>

In [229]:
B = tf.cast(tensor_2, dtype=tf.float32)
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

# Aggregating tensors

In [230]:
C = tf.constant([-7, -10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [231]:
tf.abs(C)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [232]:
e = tf.constant(np.random.randint(0, 100, size=50))
e

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([13,  5, 85, 44, 30, 35, 39, 77, 63,  0, 11, 30, 43, 46, 62, 45, 61,
       66, 58, 52, 26, 39, 35, 67, 60, 59, 59, 15, 20, 57, 57, 63, 52, 40,
       21, 60, 63, 77, 89, 34,  3, 40, 54, 22, 46,  7, 41, 56, 75, 24])>

In [233]:
tf.size(e), e.shape, e.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [234]:
# Find the minimum
tf.reduce_min(e)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [235]:
tf.reduce_max(e)

<tf.Tensor: shape=(), dtype=int64, numpy=89>

In [236]:
tf.reduce_mean(e)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [237]:
tf.reduce_sum(e)

<tf.Tensor: shape=(), dtype=int64, numpy=2226>

In [238]:
import tensorflow_probability as tfp
tfp.stats.variance(e)

<tf.Tensor: shape=(), dtype=int64, numpy=477>

In [239]:
tf.math.reduce_std(tf.cast(e, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=21.851536>

# Find the positional maximum and minimum

In [240]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [241]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [242]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [243]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [244]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing a tensor (removing all single dimensions)

In [245]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [246]:
new_g = tf.squeeze(G)

In [247]:
G.shape, new_g.shape

(TensorShape([1, 1, 1, 1, 50]), TensorShape([50]))

# One-hot encoding tensors

In [248]:
my_list = [0, 1, 2, 3]

tf.one_hot(my_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [249]:
tf.one_hot(my_list, depth=4, on_value='X', off_value='O')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'X', b'O', b'O', b'O'],
       [b'O', b'X', b'O', b'O'],
       [b'O', b'O', b'X', b'O'],
       [b'O', b'O', b'O', b'X']], dtype=object)>

# Squaring, log, square root

In [250]:
A = tf.range(1, 10)
A

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [251]:
tf.square(A)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [252]:
tf.sqrt(tf.cast(A, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [253]:
tf.math.log(tf.cast(A, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and NumPy

In [254]:
e = tf.constant(np.array([3., 7., 10.]))
e

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [255]:
numpy_e = tf.constant(np.array([3., 5., 8.]))
tensor_e = tf.constant([3., 5., 8.])

In [256]:
numpy_e.dtype, tensor_e.dtype

(tf.float64, tf.float32)