In [ ]:
!pip install datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 510.5/510.5 kB 11.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 12.5 MB/s eta 0:00:00


In [ ]:
from datasets import load_dataset

dataset = load_dataset("SeyedAli/Persian-Text-Sentiment")

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


Generating train split:   0%|          | 0/55852 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/13964 [00:00<?, ? examples/s]

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
train_df = pd.DataFrame()

In [ ]:
dataset['train']['text']

['این هندس فری تازه به دستم رسیده  و برای کسایی که انتظار شنیدن یک موسیقی با کیفیت دارن حتما پیشنهاد میکنم  بعد از شنیدن آهنگ با این هدست آدم به این فکر میکنه انگار تا حالا آهنگ نشنیده ',
 'عالی بود عالی، امیدوارم کیفیت همینجور بمونه',
 'من وقتی این ایرباد به لپ تاپ ایسوس  وصل میکنم و با نرم افزار حرفه ای   آهنگها را پخش میکنم   صدای گرم و شفافی بهم میده و نهایت قدرت این ایرباد نشون میده  ',
 'با عرض سلام ضمن عرض خسته نباشید چلوکباب کوبیده سفارشی بسیار عالی بود ولی جوجه در چلو جوجه کباب مخصوص قدری خشک بود در مجموع از نحوه سرویس دهی و زمان بندی و کیفیت غذا رضایت کامل داشته و تشکر فراوان دارم ',
 'خوشمزه و داغ مخصوصا با سس چیلی که فرستاده بودن بسیار خوب بود ممنون ازجوجه داغ و اسنپ',
 'متاسفانه با وجود تاکید زیاد به خشک و برشته نبودن نان\u200cها، نان سنگک به قدری خشک و بیسکویتی بود که قسمت عمده آن در بسته بندی کاملا خرد شده بود اطراف نان کاملا سوخته بود واقعا ناراضی بودم و خرید مجدد نخواهم کرد ',
 'طعم چیزکیک اوکی بود عالی نبود ولی اوکی بود اما بسته\u200cبندی و ارسالش بسیار نامناسب بود کی

In [ ]:
train_df['text'] = dataset['train']['text']

In [ ]:
train_df['label'] = dataset['train']['label']

In [ ]:
test_df = pd.DataFrame()

In [ ]:
test_df['text'] = dataset['test']['text']

In [ ]:
test_df['label'] = dataset['test']['label']

In [ ]:
test_df

text  label
0      مرغش خیلی پیر و ریش ریش بود واقعا بوی خیلی بد ...      0
1      کیفیت بسته بندی و زمان تحویل بسیار خوب و مناسب...      1
2                                عالی غذا مثل همیشه عالی      1
3                                زود اومد خوب و تازه بود      1
4      مقدار نوتلای این چیز کیک خیلی کم و ناچیزه یک ل...      1
...                                                  ...    ...
13959  خیلی خیلی خیلی بد مواد اولیه مانده و بد طعم، پ...      0
13960  متاسفانه نان علی رغم پیش سفارش یک ساعت دیرتر ا...      0
13961                        زیاد تعریف نداشت بی مزه بود      0
13962  به موقع رسید، برخورد پیک خوب بود، کیفیت پیتزا ...      1
13963                               عالی بود پرس تک نفره      1

[13964 rows x 2 columns]

In [ ]:
train_df.append(test_df, ignore_index=True)

<ipython-input-12-1fc0dd1826ca>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  train_df.append(test_df, ignore_index=True)


text  label
0      این هندس فری تازه به دستم رسیده  و برای کسایی ...      1
1            عالی بود عالی، امیدوارم کیفیت همینجور بمونه      1
2      من وقتی این ایرباد به لپ تاپ ایسوس  وصل میکنم ...      1
3      با عرض سلام ضمن عرض خسته نباشید چلوکباب کوبیده...      1
4      خوشمزه و داغ مخصوصا با سس چیلی که فرستاده بودن...      1
...                                                  ...    ...
69811  خیلی خیلی خیلی بد مواد اولیه مانده و بد طعم، پ...      0
69812  متاسفانه نان علی رغم پیش سفارش یک ساعت دیرتر ا...      0
69813                        زیاد تعریف نداشت بی مزه بود      0
69814  به موقع رسید، برخورد پیک خوب بود، کیفیت پیتزا ...      1
69815                               عالی بود پرس تک نفره      1

[69816 rows x 2 columns]

In [ ]:
df = pd.concat([train_df, test_df], ignore_index=True)
df

text  label
0      این هندس فری تازه به دستم رسیده  و برای کسایی ...      1
1            عالی بود عالی، امیدوارم کیفیت همینجور بمونه      1
2      من وقتی این ایرباد به لپ تاپ ایسوس  وصل میکنم ...      1
3      با عرض سلام ضمن عرض خسته نباشید چلوکباب کوبیده...      1
4      خوشمزه و داغ مخصوصا با سس چیلی که فرستاده بودن...      1
...                                                  ...    ...
69811  خیلی خیلی خیلی بد مواد اولیه مانده و بد طعم، پ...      0
69812  متاسفانه نان علی رغم پیش سفارش یک ساعت دیرتر ا...      0
69813                        زیاد تعریف نداشت بی مزه بود      0
69814  به موقع رسید، برخورد پیک خوب بود، کیفیت پیتزا ...      1
69815                               عالی بود پرس تک نفره      1

[69816 rows x 2 columns]

In [ ]:
train_df.label.value_counts()

1    27926
0    27926
Name: label, dtype: int64

In [ ]:
train_df[:10]

text  label
0  این هندس فری تازه به دستم رسیده  و برای کسایی ...      1
1        عالی بود عالی، امیدوارم کیفیت همینجور بمونه      1
2  من وقتی این ایرباد به لپ تاپ ایسوس  وصل میکنم ...      1
3  با عرض سلام ضمن عرض خسته نباشید چلوکباب کوبیده...      1
4  خوشمزه و داغ مخصوصا با سس چیلی که فرستاده بودن...      1
5  متاسفانه با وجود تاکید زیاد به خشک و برشته نبو...      0
6  طعم چیزکیک اوکی بود عالی نبود ولی اوکی بود اما...      0
7                 جوجه کباب خیلی پخته و خشک شده بود       0
8  سالاد فصل بسیار کیفیت بدی داشت وکاهوداخل ساندو...      0
9    من  تا مایع ظرفشویی سفارش دادم ولی یکی ارسال شد      0

In [ ]:
train_df_shuffled = train_df.sample(frac=1, random_state=42) # shuffle with random_state=42 for reproducibility
train_df_shuffled.head()

text  label
26452                    رفتار پیک بسیار محترمانه ممنون       1
13328    کارکنان این سوپر مارکت واقعا مسیول و منصف هستند      1
31902  حجم کم و بی کیفیت، پوره سیب زمینی بیمزه و دورچ...      0
38657  پیتزا واقعا بد بود، فیله خوب بود در کل دیگر سف...      1
35981  واقعا برای این رستوران متاسفم من ٢٢٫٤٠ سفارش د...      0

In [ ]:
from tensorflow.keras.layers import TextVectorization

text_vecorizer = TextVectorization(max_tokens=None,
                                   standardize='lower_and_strip_punctuation',
                                   split='whitespace',
                                   ngrams=None,
                                   output_mode="int",
                                   output_sequence_length=None)

In [ ]:
from sklearn.model_selection import train_test_split
train_sentence, val_sentence, train_label, val_label = train_test_split(train_df_shuffled["text"].to_numpy(),
                                                                            train_df_shuffled["label"].to_numpy(),
                                                                            test_size=0.1, # dedicate 10% of samples to validation set
                                                                            random_state=42)

In [ ]:
train_sentence

array(['بر خلاف ظاهر هیجان انگیز این پیتزا تجربه\u200cای نبود که بخوام دوباره تکرارش کنم مزه پیتزا داخل حجم زیاد پنیر روی پیتزا گم بود و نون ضخیم دور پیتزا مثل این بود که پیتزا رو گذاشتی لای یه نون باگت کلفت و داری می\u200cخوری که اصلا خوشایند نبود ',
       'پیتزا چانو، گوشتش خیلی بد بود و اصلا بافتش شبیه گوشت نبود، بیشتر شبیه کالباس بود ولی شک دارم حتی کالباس بوده باشد این آخرین سفارش از پیتزا سیبه',
       'مقداری شور بود و دیر ارسال شد', ...,
       'کیفیت صداش خوبه   اینکه چه مدت سالم بمونه رو خدا می دونه ',
       'واسه کار های سنگین نیست  اما خب جواب کار های روز مره رو میده ',
       'پیتزا بیکن افتضاح بوی بد میداد، تیکه\u200cهای فیله انگار که با چسب چسبونده شده بود انقد که مونده بود و بوی بد گرفته بود …سیب زمینی هم کاملا مشخص بود که برای یک هفته پیش بود واقعا متاسفم'],
      dtype=object)

In [ ]:
train_label

array([0, 0, 1, ..., 1, 1, 0])

In [ ]:
val_sentence

array(['ساندویچ خیلی خوشمزه بود کالباس هاش تازه بود',
       'فاجعه بود بسیار بد طعم و کهنه ',
       'لطفا به زمان ارسال دقت کنید دو ساعت و نیم زودتر سفارش رو اوردید هزینه ارسال هم در تو اسنپ  تومنه تو فاکتور ',
       ..., 'خیلی خوش مزه و لذیذ و پر ملات',
       'بدترین رستوران و غذایی که تا بحال دیدم و خوردم',
       'نون پیتزا بی نظیر بود و کیفیت مواد بسیار بالا بود فقط به نظر من نسبت به قیمتش کمی کوچیکه '],
      dtype=object)

In [ ]:
val_label

array([1, 0, 0, ..., 1, 0, 1])

In [ ]:
max_vocab_length = 100000
max_length = 100
text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
    standardize="lower_and_strip_punctuation",
    split="whitespace",
    ngrams=None,
    output_mode="int",
    output_sequence_length=max_length,
    pad_to_max_tokens=False,
    vocabulary=None,
    idf_weights=None,
    sparse=False,
    ragged=False,
    encoding="utf-8",
    name=None)

In [ ]:
text_vectorizer.adapt(train_sentence)

In [ ]:
sample_text = 'رول چایی خوب بود گاتا طعم و مزه جالبی نداشت و به نظر تازه هم نبود'
text_vectorizer([sample_text])

<tf.Tensor: shape=(1, 100), dtype=int64, numpy=
array([[2223, 3969,   12,    3, 2200,   34,    2,   55, 1050,   54,    2,
           5,  113,   41,    8,   22,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0]])>

In [ ]:
word_in_vocab = text_vectorizer.get_vocabulary()
top_5 = word_in_vocab[:5]
last_5 = word_in_vocab[-5:]
print(top_5)
print(last_5)

['', '[UNK]', 'و', 'بود', 'که']
['آباد؛', 'آالعاده', '؟؟؟؟؟؟؟', '؟؟؟؟؟؟', '؟؟،']


In [ ]:
embedding = tf.keras.layers.Embedding(input_dim=max_vocab_length,
                                      output_dim=128,
                                      embeddings_initializer="uniform",
                                      input_length=max_length)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

model0 = Pipeline([
    ('tfidf', TfidfVectorizer()),
    ('clf', MultinomialNB())
])

model0.fit(train_sentence, train_label)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [ ]:
baseline_score = model0.score(val_sentence, val_label)
baseline_score

0.8379878267096312

In [ ]:
baseline_predict = model0.predict(val_sentence)
print(f'The baseline predict is: {baseline_predict[:10]}\n')
print(f'The real label is: {val_label[:10]}')

The baseline predict is: [1 0 0 1 0 0 0 1 1 1]

The real label is: [1 0 0 1 0 0 0 1 1 1]


In [ ]:
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_result(y_true, y_pred):
  model_accuracy = accuracy_score(y_true, y_pred)
  model_precision, model_recall, f1_model, _ = precision_recall_fscore_support(y_true, y_pred, average='weighted')
  model_result = {'Accuracy':model_accuracy,
                  'Precision':model_precision,
                  'Recall':model_recall,
                  'F1_score':f1_model}
  return model_result

In [ ]:
calculate_result(y_true=val_label,
                 y_pred=baseline_predict)

{'Accuracy': 0.8379878267096312,
 'Precision': 0.8461035287784403,
 'Recall': 0.8379878267096312,
 'F1_score': 0.8374511174672209}

## Model 1: A simple dense model

In [ ]:
tf.random.set_seed(42)

inputs = tf.keras.layers.Input(shape=(1, ), dtype='string')
x = text_vectorizer(inputs)
x = embedding(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model1 = tf.keras.Model(inputs, outputs)

model1.compile(loss=tf.keras.losses.BinaryCrossentropy(),
               optimizer=tf.keras.optimizers.Adam(),
               metrics=['accuracy'])
model1.fit(train_sentence,
          train_label,
          epochs=5,
          validation_data=(val_sentence, val_label))

Epoch 1/5
1571/1571 [==============================] - 40s 23ms/step - loss: 0.4838 - accuracy: 0.7946 - val_loss: 0.3724 - val_accuracy: 0.8478
Epoch 2/5
1571/1571 [==============================] - 14s 9ms/step - loss: 0.3466 - accuracy: 0.8605 - val_loss: 0.3570 - val_accuracy: 0.8548
Epoch 3/5
1571/1571 [==============================] - 13s 9ms/step - loss: 0.3218 - accuracy: 0.8711 - val_loss: 0.3539 - val_accuracy: 0.8554
Epoch 4/5
1571/1571 [==============================] - 12s 8ms/step - loss: 0.3049 - accuracy: 0.8789 - val_loss: 0.3585 - val_accuracy: 0.8514
Epoch 5/5
1571/1571 [==============================] - 12s 8ms/step - loss: 0.2899 - accuracy: 0.8848 - val_loss: 0.3591 - val_accuracy: 0.8523


In [ ]:
model1_pred_prob = model1.predict(val_sentence)
model1_pred_prob[:10]

175/175 [==============================] - 1s 4ms/step


array([[8.9520901e-01],
       [3.4133006e-02],
       [2.1278302e-01],
       [9.6768314e-01],
       [2.3275295e-04],
       [1.2280933e-03],
       [2.5317889e-02],
       [9.2736107e-01],
       [9.9968600e-01],
       [9.9946648e-01]], dtype=float32)

In [ ]:
model1_predict = tf.squeeze(tf.round(model1_pred_prob))
model1_predict

<tf.Tensor: shape=(5586,), dtype=float32, numpy=array([1., 0., 0., ..., 1., 0., 1.], dtype=float32)>

In [ ]:
model_1_results = calculate_result(y_true=val_label,
                                    y_pred=model1_predict)
model_1_results

{'Accuracy': 0.8523093447905478,
 'Precision': 0.8529663531059597,
 'Recall': 0.8523093447905478,
 'F1_score': 0.8523366814377253}

In [ ]:
inputs = tf.keras.layers.Input(shape=(1, ), dtype='string')
x = text_vectorizer(inputs)
x = embedding(x)
x = tf.keras.layers.LSTM(64)(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model2 = tf.keras.Model(inputs, outputs)

model2.compile(loss=tf.keras.losses.BinaryCrossentropy(),
               optimizer=tf.keras.optimizers.Adam(),
               metrics=['accuracy'])
model2.fit(train_sentence,
           train_label,
           epochs=5,
           validation_data=(val_sentence, val_label))

Epoch 1/5
1571/1571 [==============================] - 73s 44ms/step - loss: 0.4302 - accuracy: 0.8228 - val_loss: 0.4466 - val_accuracy: 0.8280
Epoch 2/5
1571/1571 [==============================] - 32s 20ms/step - loss: 0.4653 - accuracy: 0.7872 - val_loss: 0.5558 - val_accuracy: 0.6853
Epoch 3/5
1571/1571 [==============================] - 29s 19ms/step - loss: 0.5724 - accuracy: 0.6586 - val_loss: 0.5663 - val_accuracy: 0.7200
Epoch 4/5
1571/1571 [==============================] - 28s 18ms/step - loss: 0.6169 - accuracy: 0.6013 - val_loss: 0.6921 - val_accuracy: 0.5159
Epoch 5/5
1571/1571 [==============================] - 29s 19ms/step - loss: 0.5714 - accuracy: 0.6713 - val_loss: 0.4531 - val_accuracy: 0.8221


In [ ]:
import tensorflow_hub as hub

embedd = hub.load('https://www.kaggle.com/models/google/nnlm/frameworks/TensorFlow2/variations/de-dim128/versions/1')

In [ ]:
sample = embedd(['کیفیت صداش خوبه   اینکه چه مدت سالم بمونه رو خدا می دونه'])
sample

<tf.Tensor: shape=(1, 128), dtype=float32, numpy=
array([[ 0.15960488, -0.07707916, -0.03910071, -0.16124356,  0.02008295,
        -0.01440455,  0.07353228,  0.05151495, -0.11357477, -0.0283043 ,
         0.04594732, -0.17522103,  0.02064349, -0.05568245, -0.07164109,
        -0.21684699,  0.06839389,  0.06228622,  0.05145122,  0.02287582,
         0.11729542, -0.14057092, -0.2045753 , -0.13490172, -0.03507048,
         0.12624663,  0.18964027,  0.02258397,  0.07927422, -0.09024586,
        -0.12676086, -0.09452242, -0.01787575,  0.03013048,  0.22942342,
         0.06473002,  0.09796231,  0.05942531, -0.00765508,  0.0126741 ,
        -0.13061649,  0.11481624,  0.00347034, -0.07512044, -0.10095543,
         0.10041805,  0.01794378, -0.09295171, -0.060223  , -0.01255473,
        -0.16861272,  0.01328487, -0.08286522,  0.02088438, -0.09902782,
         0.17779744,  0.03262354,  0.19013937, -0.08375223, -0.04411605,
        -0.14304852,  0.17473873, -0.12788704, -0.09863223,  0.0350741 ,
 

In [ ]:
sentence_encoder_layer = hub.KerasLayer('https://tfhub.dev/google/universal-sentence-encoder/4',
                                        input_shape=[],
                                        dtype=tf.string,
                                        trainable=False,
                                        name='encoder')

In [ ]:
tf.random.set_seed(42)

model3 = tf.keras.Sequential([
    sentence_encoder_layer,
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
], name='nnlm_model')

model3.compile(loss=tf.keras.losses.BinaryCrossentropy(),
               optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
               metrics=['accuracy'])

model3.fit(train_sentence,
           train_label,
           epochs=10,
           validation_data=(val_sentence, val_label))

Epoch 1/100
1571/1571 [==============================] - 33s 16ms/step - loss: 0.5508 - accuracy: 0.7088 - val_loss: 0.5257 - val_accuracy: 0.7206
Epoch 2/100
1571/1571 [==============================] - 25s 16ms/step - loss: 0.5111 - accuracy: 0.7408 - val_loss: 0.5155 - val_accuracy: 0.7347
Epoch 3/100
1571/1571 [==============================] - 24s 15ms/step - loss: 0.4916 - accuracy: 0.7547 - val_loss: 0.5026 - val_accuracy: 0.7429
Epoch 4/100
1571/1571 [==============================] - 24s 16ms/step - loss: 0.4782 - accuracy: 0.7649 - val_loss: 0.4968 - val_accuracy: 0.7447
Epoch 5/100
1571/1571 [==============================] - 25s 16ms/step - loss: 0.4649 - accuracy: 0.7728 - val_loss: 0.4895 - val_accuracy: 0.7564
Epoch 6/100
1571/1571 [==============================] - 25s 16ms/step - loss: 0.4550 - accuracy: 0.7787 - val_loss: 0.4928 - val_accuracy: 0.7479
Epoch 7/100
1571/1571 [==============================] - 24s 15ms/step - loss: 0.4441 - accuracy: 0.7854 - val_loss: 0

KeyboardInterrupt: 

In [ ]:
tf.random.set_seed(42)

inputs = tf.keras.layers.Input(shape=(1, ), dtype='string')
x = text_vectorizer(inputs)
x = embedding(x)
x = tf.keras.layers.GlobalAveragePooling1D()(x)
x = tf.keras.layers.Dense(512, activation='relu')(x)
x = tf.keras.layers.Dense(256, activation='relu')(x)
x = tf.keras.layers.Dropout(0.2)(x)
outputs = tf.keras.layers.Dense(1, activation='sigmoid')(x)
model1 = tf.keras.Model(inputs, outputs)

model1.compile(loss=tf.keras.losses.binary_crossentropy,
               optimizer=tf.keras.optimizers.Adam(),
               metrics=['accuracy'])
model1.fit(train_sentence,
          train_label,
          epochs=5,)

Epoch 1/5
1571/1571 [==============================] - 39s 24ms/step - loss: 0.3622 - accuracy: 0.8459
Epoch 2/5
1571/1571 [==============================] - 15s 10ms/step - loss: 0.3062 - accuracy: 0.8715
Epoch 3/5
1571/1571 [==============================] - 17s 11ms/step - loss: 0.2676 - accuracy: 0.8858
Epoch 4/5
1571/1571 [==============================] - 22s 14ms/step - loss: 0.2352 - accuracy: 0.9009
Epoch 5/5
1571/1571 [==============================] - 20s 13ms/step - loss: 0.2092 - accuracy: 0.9135


In [ ]:
model_1_pred_prob = model1.predict(val_sentence)
model_1_pred_prob[:10]

175/175 [==============================] - 0s 2ms/step


array([[9.7298110e-01],
       [6.3425958e-02],
       [2.9651055e-02],
       [9.9129480e-01],
       [6.6282068e-05],
       [2.0263569e-02],
       [5.0718300e-03],
       [9.9911863e-01],
       [9.9997699e-01],
       [9.9697816e-01]], dtype=float32)

In [ ]:
model_1_predict = tf.squeeze(tf.round(model_1_pred_prob))
model_1_predict

<tf.Tensor: shape=(5586,), dtype=float32, numpy=array([1., 0., 0., ..., 1., 0., 1.], dtype=float32)>

In [ ]:
model1.predict(['عالی بود عالی، امیدوارم کیفیت همینجور بمونه'])

1/1 [==============================] - 0s 56ms/step


array([[0.99959475]], dtype=float32)

In [ ]:
!pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.0/17.0 MB 45.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.1/92.1 kB 13.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 308.2/308.2 kB 37.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.6/75.6 kB 11.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.5/138.5 kB 18.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 67.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 9.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 13.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.8/77.8 kB 6.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 8.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 kB 10.2 MB/s eta 0:00:00
  Created wheel for ffmpy: filename=ffmpy-0.3.2-py3-none-any.whl si

In [ ]:
# Save the model using the 'tf' format
model1.save('my_model', save_format='tf')

In [ ]:
# Save the model with .keras extension
model1.save('my_model.keras')

In [ ]:
from tensorflow.keras.models import load_model
model = load_model('/content/my_model.keras')

In [ ]:
model.predict('غذا خوب، تازه، گرم و خوشمزه بود با تشکر از مدیریت رستوران مهدی و همچنین تشکر ویژه از اسنپ فود')

IndexError: tuple index out of range

In [ ]:
model.predict(['غذا خوب، تازه، گرم و خوشمزه بود با تشکر از مدیریت رستوران مهدی و همچنین تشکر ویژه از اسنپ فود'])

1/1 [==============================] - 0s 280ms/step


array([[0.9999429]], dtype=float32)

In [ ]:
import gradio as gr
import tensorflow as tf
from tensorflow.keras.models import load_model
def sentiment_analysis(text):

    model = load_model('my_model.keras')

    predict = model.predict([text])
    return "positive" if predict > 0.5  else "negative"

In [ ]:
demo = gr.Interface(
    fn=sentiment_analysis,  # Your text classification function
    inputs="textbox",  # Input component (textbox for user input)
    outputs="text"  # Output component (label to display predicted sentiment)
)

# Launch the interface
demo.launch(share=True)

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://b13233b25d1c9e69c2.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


In [ ]:
model_json = model1.to_json()
with open("model111.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.keras", save_format=)
print("Saved model to disk")

NotImplementedError: Save or restore weights that is not an instance of `tf.Variable` is not supported in h5, use `save_format='tf'` instead. Received a model or layer TextVectorization with weights [<keras.src.layers.preprocessing.index_lookup.VocabWeightHandler object at 0x7d70993cb7f0>]